[theme]
base = "dark"                        
primaryColor = "#8A9CF4"             
backgroundColor = "#0e1117"          
secondaryBackgroundColor = "#1b1f2a" 
textColor = "#e5e7eb"                

font = "sans serif"                  
